<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-OV4RUVE6" name="a1_keyWordTest.B7_AlwaysRunTest" tests="6" failures="0" timestamp="02 Jan 2023 10:27:41 GMT" time="0.034" errors="1">
  <testcase name="loginApp" time="0.027" classname="a1_keyWordTest.B7_AlwaysRunTest"/>
  <testcase name="searchProduct" time="0.005" classname="a1_keyWordTest.B7_AlwaysRunTest">
    <error type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zeroat a1_keyWordTest.B7_AlwaysRunTest.searchProduct(B7_AlwaysRunTest.java:13)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- searchProduct -->
  <testcase name="addToCart" time="0.001" classname="a1_keyWordTest.B7_AlwaysRunTest"/>
  <testcase name="payment" time="0.001" classname="a1_keyWordTest.B7_AlwaysRunTest"/>
  <testcase name="cancelOrder" time="0.000" classname="a1_keyWordTest.B7_AlwaysRunTest"/>
  <testcase name="trackOrder" time="0.000" classname="a1_keyWordTest.B7_AlwaysRunTest"/>
</testsuite> <!-- a1_keyWordTest.B7_AlwaysRunTest -->
